import{S as v,i as c,a as y}from"./assets/vendor-c145bea9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&n(p)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const w=document.querySelector(".form"),l=document.querySelector(".gallery");document.querySelector(".gallery-box");const m=document.querySelector(".loader-top"),a=document.querySelector(".load-image");let i=1,d="cat",f=40;function g(){m.classList.remove("hide")}function u(){m.classList.add("hide")}const h=new v(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});w.addEventListener("submit",x);a.addEventListener("click",S);async function x(s){if(s.preventDefault(),g(),a.style.display="none",i=1,l.innerHTML="",d=s.target.elements.search.value.trim(),!d){l.innerHTML="",c.info({position:"topRight",message:"Error enter any symbols"}),u();return}try{const{data:{hits:r,totalHits:t}}=await b(d,i);r.length>0?(u(),l.innerHTML=L(r),h.refresh(),c.success({position:"topRight",message:`We found ${t} photos`}),a.style.display="block"):(l.innerHTML="",c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),t<=f&&(a.style.display="none")}catch{console.log("Error")}finally{u(),s.target.reset()}}function b(s,r){return y.defaults.baseURL="https://pixabay.com",y.get("/api/",{params:{key:"41728262-02d59bc227e0fcf400762914d",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40}})}function L(s=[]){return s.reduce((r,t)=>r+`<li class="gallery-item">
        <a href=${t.largeImageURL}>
          <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t.likes}</span></p>
          <p>views: <span class="text-value">${t.views}</span></p>
          <p>comments: <span class="text-value">${t.comments}</span></p>
          <p>downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
      </li>`,"")}async function S(s){g(),a.style.display="none";const t=document.querySelector(".gallery-item:first-child").getBoundingClientRect().height;try{i+=1;const{data:{hits:n,totalHits:e}}=await b(d,i),o=Math.ceil(e/f);if(a.style.display="block",l.insertAdjacentHTML("beforeend",L(n)),h.refresh(),i===o)return a.style.display="none",c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(n){console.log(n)}finally{u(),window.scrollBy({top:2*t,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
