import{S as v,i as c,a as p}from"./assets/vendor-c145bea9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const y of o.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&l(y)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const L=document.querySelector(".form"),d=document.querySelector(".gallery");document.querySelector(".gallery-box");const a=document.querySelector(".loader"),m=document.querySelector(".loader-btn");document.querySelector("input");const n=document.querySelector(".load-image");let i=1,u="cat",f=40;a.style.display="none";const g=new v(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});L.addEventListener("submit",S);n.addEventListener("click",q);async function S(s){if(s.preventDefault(),a.style.display="block",n.style.display="none",i=1,u=s.target.elements.search.value.trim(),!u){d.innerHTML="",c.info({position:"topRight",message:"Error enter any symbols"}),a.style.display="none";return}try{const{data:{hits:r,totalHits:t}}=await h(u,i);r.length>0?(a.style.display="none",d.innerHTML=b(r),g.refresh(),c.success({position:"topRight",message:`We found ${t} photos`}),n.style.display="block"):(d.innerHTML="",c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),t<=f&&(n.style.display="none")}catch{console.log("Error")}finally{a.style.display="none",s.target.reset()}}function h(s,r){return p.defaults.baseURL="https://pixabay.com",p.get("/api/",{params:{key:"41728262-02d59bc227e0fcf400762914d",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40}})}function b(s=[]){return s.reduce((r,t)=>r+`<li class="gallery-item">
        <a href=${t.largeImageURL}>
          <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t.likes}</span></p>
          <p>views: <span class="text-value">${t.views}</span></p>
          <p>comments: <span class="text-value">${t.comments}</span></p>
          <p>downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
      </li>`,"")}async function q(s){m.style.display="block",n.style.display="none";const t=document.querySelector(".gallery-item:first-child").getBoundingClientRect().height;try{i+=1;const{data:{hits:l,totalHits:e}}=await h(u,i),o=Math.ceil(e/f);if(n.style.display="block",d.insertAdjacentHTML("beforeend",b(l)),g.refresh(),i===o)return n.style.display="none",c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(l){console.log(l)}finally{m.style.display="none",window.scrollBy({top:2*t,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
